# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osradmin', '0005_remove_membre_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.IntegerField()),
                ('langage', models.IntegerField()),
                ('niveau', models.IntegerField()),
                ('user', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Langage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langage', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osradmin.Categorie')),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='Tel',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='membre',
            name='langue',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='membre',
            name='naissance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='pays',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
